services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.14.0
  #   container_name: logstash
  #   environment:
  #     - LS_JAVA_OPTS=-Xms2g -Xmx2g
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk
  #   volumes:
  #   - ./logstash/pipeline:/usr/share/logstash/pipeline

networks:
  elk_network:
    driver: bridge

